### ISSUE TITLE
Confusion around "Give the password inside /Modules/Scrape.py"

### ISSUE THREAD

**Issue by adchdev** [AshwinAmbal/DarkWeb-Crawling-Indexing#7]
Hi, I am not sure what to do with this instruction in the readme:

Give the password inside /Modules/Scrape.py `from stem.control import Controller with Controller.from_port(port = 9051) as controller: controller.authenticate("your_password_hash") controller.signal(Signal.NEWNYM)`

Which Modules folder?

**Comment by guneetsura** [comment]
Me neither.

Although I tried creating a Modules folder in 'crawl' folder itself and I added the code on 'Scrape.py' file. I also added the onion links in the txt file that is mentioned in the readme file.
The code does not seem to work.

>Traceback (most recent call last):
  File "/home/kali/Downloads/DarkWeb-Crawling-Indexing-master/Code/crawler/main.py", line 1, in <module>
    from crawl_bot import Crawl_bot
  File "/home/kali/Downloads/DarkWeb-Crawling-Indexing-master/Code/crawler/crawl_bot.py", line 11, in <module>
    import socks, socket
  File "/home/kali/.local/lib/python3.10/site-packages/socks.py", line 65, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/home/kali/Downloads/DarkWeb-Crawling-Indexing-master/Code/crawler/main.py", line 1, in <module>
    from crawl_bot import Crawl_bot
  File "/home/kali/Downloads/DarkWeb-Crawling-Indexing-master/Code/crawler/crawl_bot.py", line 11, in <module>
    import socks, socket
  File "/home/kali/.local/lib/python3.10/site-packages/socks.py", line 65, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
